import type { Metadata } from "next";
import { Geist, Geist_Mono, Mulish } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";
import { dark } from "@clerk/themes";
import Navbar from "./_components/navbar";
import { auth } from "@clerk/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
  weight: ["400", "600", "700", "200", "500"], // espessura da fonte
  display: "swap",
});
export const metadata: Metadata = {
  title: "Finance AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${mulish.variable} ${geistMono.variable} dark antialiased`}
      >
        <ClerkProvider
          localization={ptBR}
          appearance={{
            baseTheme: dark,
          }}
        >
          {userId && <Navbar />}
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
